// export const FAVE_RECIPE = 'FAVORITE_RECIPE';
// export const LOAD_RECIPES = 'LOAD_RECIPES';
// export const LOG_INPUT = 'LOG_INPUT';

export const TOGGLE_EDIT_MODAL = "TOGGLE_EDIT_MODAL";
export const TOGGLE_APPOINTMENT_MODAL = "TOGGLE_APPOINTMENT_MODAL";
export const SHOW_USER_LOOKUP_MODAL = "SHOW_USER_LOOKUP_MODAL";
export const STORE_USER_APPOINTMENT_INFORMATION =
  "STORE_USER_APPOINTMENT_INFORMATION";
export const STORE_APPOINTMENT_INFORMATION = "STORE_APPOINTMENT_INFORMATION";
export const EDIT_CURRENT_DATE = "EDIT_CURRENT_DATE";
